--------------------------------------------------------
-- EDUPULSE INSIGHTS: AUTOMATED DATA LOGIC FOR CHARTS
-- Step 1: Run this in SQL Scripts
--------------------------------------------------------

-- 1. DROP EXISTING OBJECTS (Fresh Start)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('EP_ASSESSMENTS', 'EP_ATTENDANCE', 'EP_STUDENTS', 'EP_BATCHES')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- 2. CREATE DATABASE STRUCTURE
CREATE TABLE ep_batches (
    batch_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_name  VARCHAR2(100) NOT NULL,
    stream      VARCHAR2(100)
);

CREATE TABLE ep_students (
    student_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    VARCHAR2(100) NOT NULL,
    batch_id     NUMBER REFERENCES ep_batches(batch_id)
);

CREATE TABLE ep_attendance (
    att_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   NUMBER REFERENCES ep_students(student_id),
    status       VARCHAR2(10) CHECK (status IN ('Present', 'Absent')),
    log_date     DATE DEFAULT SYSDATE
);

CREATE TABLE ep_assessments (
    eval_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   NUMBER REFERENCES ep_students(student_id),
    score        NUMBER CHECK (score BETWEEN 0 AND 100),
    subject      VARCHAR2(50)
);

--------------------------------------------------------
-- 3. AUTO-INSERT SAMPLE DATA (For Charts)
INSERT INTO ep_batches (batch_name, stream) VALUES ('Batch-A', 'Material Science');
INSERT INTO ep_batches (batch_name, stream) VALUES ('Batch-B', 'CS');

INSERT INTO ep_students (full_name, batch_id) VALUES ('Rahul Dev', 1);
INSERT INTO ep_students (full_name, batch_id) VALUES ('Meera Krish', 1);
INSERT INTO ep_students (full_name, batch_id) VALUES ('Kevin Sam', 2);

INSERT INTO ep_attendance (student_id, status) VALUES (1, 'Present');
INSERT INTO ep_attendance (student_id, status) VALUES (2, 'Present');
INSERT INTO ep_attendance (student_id, status) VALUES (3, 'Absent');

INSERT INTO ep_assessments (student_id, score, subject) VALUES (1, 88, 'Quiz-1');
INSERT INTO ep_assessments (student_id, score, subject) VALUES (2, 72, 'Quiz-1');
INSERT INTO ep_assessments (student_id, score, subject) VALUES (3, 95, 'Quiz-1');

COMMIT;

--------------------------------------------------------
-- 4. THE MAGIC: PRE-CONFIGURED VIEWS FOR CHARTS
-- Charts-la "SQL Query" pattiya indha view names-a mattum use pannunga.
--------------------------------------------------------

-- For Bar Chart (Student Performance)
CREATE OR REPLACE VIEW chart_performance AS
SELECT full_name AS label, score AS value FROM ep_students s 
JOIN ep_assessments a ON s.student_id = a.student_id;

-- For Donut/Pie Chart (Attendance)
CREATE OR REPLACE VIEW chart_attendance AS
SELECT status AS label, COUNT(*) AS value FROM ep_attendance GROUP BY status;

-- For Summary Report
CREATE OR REPLACE VIEW chart_summary AS
SELECT b.batch_name, COUNT(s.student_id) as total_students 
FROM ep_batches b LEFT JOIN ep_students s ON b.batch_id = s.batch_id 
GROUP BY b.batch_name;